# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/A7.xdc

# IP: ip/Seg7_Dev_0/Seg7_Dev_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_0 || ORIG_REF_NAME==Seg7_Dev_0} -quiet] -quiet
