# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/A7.xdc

# IP: ip/Seg7_Dev_0/Seg7_Dev_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_0 || ORIG_REF_NAME==Seg7_Dev_0} -quiet] -quiet

# IP: ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/ROM_B/ROM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_B || ORIG_REF_NAME==ROM_B} -quiet] -quiet

# XDC: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM/RAM_ooc.xdc

# XDC: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_B/ROM_B_ooc.xdc
