# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Karnage/ZJU/Courses/23-24SpSu/CO/Labs/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
